server:
    port: 8829
    context-path: /
    compression:
      enabled: true
      mime-types: application/json,application/xml,text/html,text/xml,text/plain

spring:
    datasource:
        url: jdbc:mysql://127.0.0.1:3306/flower_intellij?useUnicode=true&characterEncoding=UTF-8&createDatabaseIfNotExist=true
        username: root
        password:
        tomcat:
            test-on-borrow: true
            validation-query: SELECT 1
            max-active: 10
            max-idle: 10
            min-idle: 5
            initial-size: 1
    jpa:
        hibernate:
            ddl-auto: none
            dialect: org.hibernate.dialect.MySQLDialect
            naming:
                physical-strategy: org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
            format_sql: true
    application:
      name: flower
liquibase:
  changeLog: classpath:db/changelog/master.xml

logging:
    level:
        com.hibernate.demo: DEBUG
        org.hibernate.SQL: DEBUG
